version: '3.8'
name: tsk_dependencies
services:
  store-postgres:
    image: postgres
    container_name: tsk_dependencies_store_postgres
    restart: always
    ports:
      - 5072:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - store_postgres_volume:/var/lib/postgresql/data
  store_pgadmin:
    image: dpage/pgadmin4
    container_name: tsk_dependencies_store_pgadmin
    restart: always
    ports:
      - 5073:80
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    volumes:
      - store_pgadmin_volume:/var/lib/pgadmin
  auth-postgres:
    image: postgres
    container_name: tsk_dependencies_auth_postgres
    restart: always
    ports:
      - 5082:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - auth_postgres_volume:/var/lib/postgresql/data
  auth_pgadmin:
    image: dpage/pgadmin4
    container_name: tsk_dependencies_auth_pgadmin
    restart: always
    ports:
      - 5083:80
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    volumes:
      - auth_pgadmin_volume:/var/lib/pgadmin

volumes:
  store_postgres_volume:
  store_pgadmin_volume:
  auth_postgres_volume:
  auth_pgadmin_volume:
