version: '3.8'
services:
  postgres:
    image: postgres
    container_name: PostgreSQL
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql_volume:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: PgAdmin
    restart: always
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_volume:/var/lib/pgadmin

volumes:
  postgresql_volume:
  pgadmin_volume: