version: '3.8'
name: tsk_dependencies
services:
  api:
    container_name: tsk_api
    build: ./Tsk.HttpApi
    ports:
      - 5071:8080
    environment:
      ConnectionStrings__PostgreSQL: 'Server=postgres;Port=5432;Database=postgres;User Id=postgres;Password=postgres'
  postgres:
    image: postgres
    container_name: tsk_postgres
    restart: always
    ports:
      - 5072:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: tsk_pgadmin
    restart: always
    ports:
      - 5073:80
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    volumes:
      - pgadmin_volume:/var/lib/pgadmin

volumes:
  postgres_volume:
  pgadmin_volume:
