name: Lint Solution

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-solution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - run: dotnet restore
      - run: dotnet build --no-restore
      - run: dotnet format --verify-no-changes
